version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - pow-network

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      server:
        condition: service_healthy
    command: ["/app/client", "-addr", "server:8080", "-n", "10"]
    networks:
      - pow-network

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      server:
        condition: service_healthy
    command: ["/app/client", "-addr", "server:8080", "-n", "10"]
    networks:
      - pow-network

  client3:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      server:
        condition: service_healthy
    command: ["/app/client", "-addr", "server:8080", "-n", "10"]
    networks:
      - pow-network

networks:
  pow-network:
    driver: bridge 